MKSHELL=/bin/bash
#Definir MKSHELL ahora debe ir siempre arriba con /bin/bash. "Todo lo que viene a continuación interprétalo con bash"

#Este bloque separa los multialélicos, normaliza y deja solo snps
%.split.normalized.only_snps.vcf:Q: %.split.normalized.tmp
	echo "[DEBUG] dejando solo snps"
	bcftools view \
		--exclude-uncalled \
		--types snps \
		--output-file $target \
		$prereq \
	&& rm $stem.*.tmp

%.split.normalized.tmp:Q: %.vcf
	echo "[DEBUG] normalizando"
	bcftools norm \
		--multiallelics -any \
		--fasta-ref $GENOME_REFERENCE \
		$prereq \
		--output $target
