MKSHELL=/bin/bash
#Definir MKSHELL ahora debe ir siempre arriba con /bin/bash. "Todo lo que viene a continuación interprétalo con bash"

#Este bloque quita las muestras no deseadas.
%.samples_removed.vcf:Q: %.vcf.gz
	bcftools view --samples-file $SAMPLE --force-samples --output-file $target.build $prereq \
	&& mv $target.build $target
